# Generated by Django 2.1 on 2018-08-22 19:53

from django.db import migrations

def seed_lookup_data(apps, schema_editor):
    # Seed Wine Category data
    wineCategories = ('Red', 'White')
    WineCategory = apps.get_model('api', 'WineCategory')

    for wineCategory in wineCategories:
        category = WineCategory(name=wineCategory)
        category.save()

    # Seed Wine Varietal data
    redWineVarietals = ('Merlot', 'Syrah', 'Red Blend', 'Cabernet Sauvignon', 'Cabernet Franc', 'Grenache', 'Malbec', 'Mourvedre', 'Nebbiolo', 
                        'Pinot Noir', 'Sangiovese', 'Zinfandel')
    whiteWineVarietals = ('Chardonnay', 'Riesling', 'Sauvignon Blanc', 'Pinot Grigio', 'Chenin Blanc', 'Moscato', 'White Blend', 'Rose', 'Semillon',
                          'Viognier', 'Gewurztraminer')

    WineVarietal = apps.get_model('api', 'WineVarietal')

    for redWineVarietal in redWineVarietals:
        redVarietal = WineVarietal(name=redWineVarietal, category=WineCategory.objects.get(name='Red'))
        redVarietal.save()

    for whiteWineVarietal in whiteWineVarietals:
        whiteVarietal = WineVarietal(name=whiteWineVarietal, category=WineCategory.objects.get(name='White'))
        whiteVarietal.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_lookup_data)
    ]
