# Generated by Django 2.1 on 2018-08-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180822_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wine',
            options={'ordering': ('winery', 'name')},
        ),
        migrations.AlterField(
            model_name='winery',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='WineRegion',
        ),
    ]
