# Generated by Django 2.1 on 2018-08-24 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20180822_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cellar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('purchase_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cellar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('owner', 'purchase_date'),
            },
        ),
        migrations.RemoveField(
            model_name='winery',
            name='region',
        ),
        migrations.AlterField(
            model_name='wine',
            name='winery',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cellar',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Wine'),
        ),
    ]
