# Generated by Django 2.1 on 2018-08-24 17:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180824_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedCellar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('consumption_date', models.DateField()),
                ('notes', models.CharField(max_length=250)),
                ('personal_rating', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cellar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cellar')),
            ],
            options={
                'ordering': ('consumption_date',),
            },
        ),
    ]
